#ifndef PINS_H
#define PINS_H

#define HUMEDAD_SUSTRATO_1 34
#define HUMEDAD_SUSTRATO_2 35
#define HUMEDAD_SUSTRATO_3 32
#define RELAY_ELECTROVALVULA_1 4
#define RELAY_ELECTROVALVULA_2 5
#define RELAY_ELECTROVALVULA_3 18
#define DHTPIN 16

#endif // PINS_H