services:
  plantix:
    build:
      context: ../../application/plantix
      dockerfile: Dockerfile
    container_name: plantix # <-- CAMBIO: Nombre simplificado
    volumes:
      - ../../application/plantix:/app
    environment:
      # DB (sin cambios)
      MYSQL_DB_USERNAME: "${MYSQL_DB_USERNAME}"
      MYSQL_DB_PASSWORD: "${MYSQL_DB_PASSWORD}"
      MYSQL_DB_NAME: "${MYSQL_DB_NAME}"
      
      # Puerto (sin cambios)
      PORT: "${APP_PORT}"

      # <-- INICIO DE CAMBIOS IMPORTANTES -->
      # SMTP Gmail (Nombres de variables corregidos para que coincidan con la app)
      MAIL_USERNAME: "${EMAIL}"
      MAIL_PASSWORD: "${APP_PASSWORD}"
      ALERT_DEFAULT_RECIPIENTS: "${EMAIL}"

      # MQTT (URL agregada para que la app sepa dónde conectar)
      MQTT_URL: "tcp://broker-mosquitto:1883"
      # <-- FIN DE CAMBIOS IMPORTANTES -->

      # Devtools (sin cambios)
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      plantix-db:
        condition: service_healthy
      broker-mosquitto: # <-- CAMBIO: Dependencia agregada
        condition: service_started

  plantix-db:
    image: mysql:8.0
    container_name: plantix-db
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_MYSQL_ROOT_PASSWORD}"
    restart: unless-stopped
    volumes:
      - plantix_db_data:/var/lib/mysql
      - ../../application/plantixDB:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s

  broker-mosquitto:
    image: eclipse-mosquitto
    container_name: broker-mosquitto # <-- Buena práctica añadir nombre de contenedor
    ports:
      - 1883:1883
    volumes:
      - ../../brokerMQTT/config:/mosquitto/config
      - ../../brokerMQTT/data:/mosquitto/data
      - ../../brokerMQTT/log:/mosquitto/log
    restart: unless-stopped # <-- Buena práctica añadir política de reinicio

volumes:
  plantix_db_data:
  
